/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK - Request successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default true */
                            success: boolean;
                            /** @default Operation completed successfully */
                            message: string;
                            /** @default 200 */
                            statusCode: number;
                        };
                    };
                };
                /** @description Unprocessable Entity - Validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default false */
                            success: boolean;
                            error: {
                                /** @default Request validation failed */
                                message: string;
                                issues?: {
                                    message: string;
                                    path?: string;
                                    code?: string;
                                }[];
                            };
                            /** @default 422 */
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mailer/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use Resend Mailers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Recipient email address(es) */
                        to: string | string[];
                        /** @description Email subject */
                        subject: string;
                        /** @description HTML content of the email */
                        html?: string;
                        /** @description Plain text content of the email */
                        text?: string;
                        /**
                         * Format: email
                         * @description Sender email address
                         */
                        from?: string;
                        /**
                         * Format: email
                         * @description Reply-to email address
                         */
                        replyTo?: string;
                        /** @description CC email address(es) */
                        cc?: string | string[];
                        /** @description BCC email address(es) */
                        bcc?: string | string[];
                    };
                };
            };
            responses: {
                /** @description OK - Request successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default true */
                            success: boolean;
                            /** @default Operation completed successfully */
                            message: string;
                            /** @default 200 */
                            statusCode: number;
                        };
                    };
                };
                /** @description Bad Request - Invalid request data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default false */
                            success: boolean;
                            error: {
                                /** @default Invalid request parameters provided */
                                message: string;
                                issues?: {
                                    message: string;
                                    path?: string;
                                    code?: string;
                                }[];
                            };
                            /** @default 400 */
                            statusCode: number;
                        };
                    };
                };
                /** @description Unprocessable Entity - Validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default false */
                            success: boolean;
                            error: {
                                /** @default Request validation failed */
                                message: string;
                                issues?: {
                                    message: string;
                                    path?: string;
                                    code?: string;
                                }[];
                            };
                            /** @default 422 */
                            statusCode: number;
                        };
                    };
                };
                /** @description Internal Server Error - Server encountered an error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default false */
                            success: boolean;
                            error: {
                                /** @default An unexpected error occurred */
                                message: string;
                                issues?: {
                                    message: string;
                                    path?: string;
                                    code?: string;
                                }[];
                            };
                            /** @default 500 */
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
